export const SET_ARTICLES = 'SET_ARTICLES'

export const SET_CURRENT_ARTICLE_ID = 'SET_CURRENT_ARTICLE_ID'

export const SET_CURRENT_ARTICLE_TITLE = 'SET_CURRENT_ARTICLE_TITLE'

export const SET_BGIMG = 'SET_BGIMG'

export const SET_LASTID = 'SET_LASTID'

export const SET_COUNT = 'SET_COUNT'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const SET_NUM_PER_PAGE = 'SET_NUM_PER_PAGE'

export const SET_SINGLE_ARTICLE = 'SET_SINGLE_ARTICLE'
